name: reviewdog (Python)
on:
  pull_request:
    paths:
      - '**/*.py'

permissions:
  pull-requests: write
  contents: read

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run flake8
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          flake8_args: "--config .flake8"
          filter_mode: "diff_context"
          fail_level: "error"

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup mypy
        run: |
          pip install mypy mypy-extensions
          pip freeze | grep mypy

      - name: Run mypy
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m mypy --config-file .mypy.ini . | \
            reviewdog -f="mypy" -name="mypy" -reporter="github-pr-review" -filter-mode="diff_context" -fail-level="any" -level="warning"
